name: Development workflow

on:
  push:
    branches:
      - develop

jobs:
  deploy_server:
    runs-on: ubuntu-latest
    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Building Server
        working-directory: server
        run: npm install && npm run build --if-present
      - name: Deploy server to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --dev
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'todo-test-build-server'
          heroku_email: 'eduarte2205@gmail.com'

